/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;

/**
 *
 * @author Jonathan
 */
public class Sketch1 extends javax.swing.JPanel {

    /**
     * Creates new form Sketch1
     */
    public Sketch1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Welcome Username");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 131, 25));

        jLabel2.setText("Courses");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 56, -1, -1));

        jButton1.setText("Add Course");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 97, 127, -1));

        jButton2.setText("Delete Course");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 140, 127, -1));

        jButton3.setText("Modify Course");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 183, 127, -1));

        jLabel3.setText("Semesters");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 226, -1, -1));

        jButton4.setText("Add Semester");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 260, 127, -1));

        jButton5.setText("Delete Semester");
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 303, -1, -1));

        jButton6.setText("Modify Semester");
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 346, -1, -1));

        jTabbedPane5.addTab("Fall 2014", jTabbedPane1);
        jTabbedPane5.addTab("Spring 2014", jTabbedPane2);
        jTabbedPane5.addTab("Fall 2015", jTabbedPane4);
        jTabbedPane5.addTab("Spring 2015", jTabbedPane3);

        add(jTabbedPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 67, 430, 310));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    // End of variables declaration//GEN-END:variables
}
